// Tests de funciones puras del frontend: `npm test` (node --test, sin navegador)
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { parseGcodeText, parseDuration, gramsFromMeters } from '../src/lib/gcode.ts'

test('PrusaSlicer: gramos, metros, tiempo y slicer', () => {
  const info = parseGcodeText(`; generated by PrusaSlicer 2.7.1
; filament used [mm] = 5234.21
; filament used [g] = 15.61
; estimated printing time (normal mode) = 1h 23m 45s`)
  assert.deepEqual(info, { grams: 15.61, meters: 5.23421, seconds: 5025, slicer: 'PrusaSlicer 2.7.1' })
})

test('Cura: metros y ;TIME', () => {
  const info = parseGcodeText(`;FLAVOR:Marlin
;TIME:3723
;Filament used: 2.53245m
;Generated with Cura_SteamEngine 5.7.0`)
  assert.deepEqual(info, { meters: 2.53245, seconds: 3723, slicer: 'Cura_SteamEngine 5.7.0' })
})

test('OrcaSlicer multi-extrusor suma y prefiere el tiempo total', () => {
  const info = parseGcodeText(`; generated by OrcaSlicer 2.1.1
; filament used [mm] = 1000.00, 500.00
; filament used [g] = 3.00, 1.50
; model printing time: 2h 5m 3s; total estimated time: 2h 10m 3s`)
  assert.deepEqual(info, { grams: 4.5, meters: 1.5, seconds: 7803, slicer: 'OrcaSlicer 2.1.1' })
})

test('Bambu Studio', () => {
  const info = parseGcodeText(`; BambuStudio 01.09.00.70
; total filament weight [g] : 22.47
; total estimated time: 1d 2h 0m 0s`)
  assert.deepEqual(info, { grams: 22.47, seconds: 93600, slicer: 'BambuStudio 01.09.00.70' })
})

test('sin metadatos', () => {
  assert.deepEqual(parseGcodeText('G28\nG1 X10'), {})
})

test('duraciones y gramos desde metros', () => {
  assert.equal(parseDuration('1d 2h 3m 4s'), 93784)
  assert.equal(parseDuration('sin tiempo'), undefined)
  assert.equal(Math.round(gramsFromMeters(1, 1.24) * 100) / 100, 2.98) // 1 m de PLA 1.75 mm
})
